#!/bin/bash

# Test All 20 Example Queries
# Make sure your FastAPI server is running on http://localhost:8000

echo "🚀 Testing All 20 Example Queries from request.md"
echo "=================================================="

# Create results directory
mkdir -p query_results
timestamp=$(date +"%Y%m%d_%H%M%S")

# Function to run query and save result
run_query() {
    local query_num=$1
    local query_text=$2
    
    echo "📝 Running Query $query_num..."
    echo "Query: $query_text"
    
    curl -s -X POST "http://localhost:8000/api/v1/query" \
      -H "Content-Type: application/json" \
      -d "{\"query\": \"$query_text\"}" \
      | jq '.' > "query_results/query_${query_num}_${timestamp}.json"
    
    echo "✅ Query $query_num completed - saved to query_results/query_${query_num}_${timestamp}.json"
    echo "---"
    sleep 1
}

# Query 1
run_query "01" "What is the email address of the employee who is the Sales Manager?"

# Query 2
run_query "02" "Which employee in the company works in the Product Development department?"

# Query 3
run_query "03" "What was the sales revenue of 'Wei Zhang' for the week starting on '2024-08-28'?"

# Query 4
run_query "04" "Who are the employees working in the 'Finance' department?"

# Query 5
run_query "05" "Retrieve the total number of meetings attended by 'Na Li' in her weekly updates."

# Query 6
run_query "06" "Which employees worked more than 40 hours during week 1?"

# Query 7
run_query "07" "How many employees does the company have in total?"

# Query 8
run_query "08" "What is the average hours worked by all employees during week 2?"

# Query 9
run_query "09" "How much total sales revenue has the Sales department generated to date?"

# Query 10
run_query "10" "What is the total sales revenue generated by the company during week 1?"

# Query 11
run_query "11" "Who worked the most hours during the first week of September 2024?"

# Query 12
run_query "12" "Which employee attended the most meetings during week 2?"

# Query 13
run_query "13" "Which employees in the company were hired during a time of industry recession?"

# Query 14
run_query "14" "Who are the employees that faced challenges with customer retention, and what solutions did they propose?"

# Query 15
run_query "15" "Which employees work in roles that likely require data analysis or reporting skills?"

# Query 16
run_query "16" "List all employees who work in the IT department within the company."

# Query 17
run_query "17" "Compare the hours worked by 'Wei Zhang' and 'Tao Huang' during week 1."

# Query 18
run_query "18" "Who are the top 3 employees by total hours worked during the last 4 weeks?"

# Query 19
run_query "19" "Who achieved the highest sales revenue in a single week, and when?"

# Query 20
run_query "20" "What is the total number of hours worked and average sales revenue for employees in the Business Development department?"

echo ""
echo "🎉 All 20 queries completed!"
echo "Results saved in query_results/ directory"
echo ""
echo "📊 Running benchmark for summary..."
curl -s -X POST "http://localhost:8000/api/v1/benchmark" \
  -H "Content-Type: application/json" \
  | jq '.' > "query_results/benchmark_summary_${timestamp}.json"

echo "✅ Benchmark summary saved to query_results/benchmark_summary_${timestamp}.json"
echo ""
echo "📁 Files created:"
ls -la query_results/*${timestamp}* 