#!/bin/bash

echo "🔍 Testing All 20 Example Queries from request.md"
echo "================================================="

echo "📊 Query 1: What is the email address of the employee who is the Sales Manager?"
psql -d employee_tracker -c "SELECT email, full_name FROM employees WHERE job_title = 'Sales Manager';"

echo -e "\n📊 Query 2: Which employee in the company works in the Product Development department?"
psql -d employee_tracker -c "SELECT full_name, job_title, email FROM employees WHERE department = 'Product Development';"

echo -e "\n📊 Query 3: What was the sales revenue of 'Wei Zhang' for the week starting on '2024-08-28'?"
psql -d employee_tracker -c "SELECT e.full_name, ea.total_sales, cw.start_date, cw.end_date FROM employees e JOIN employee_activities ea ON e.id = ea.employee_id JOIN calendar_weeks cw ON ea.week_number = cw.week_number WHERE e.full_name = 'Wei Zhang' AND cw.start_date <= '2024-08-28' AND cw.end_date >= '2024-08-28';"

echo -e "\n📊 Query 4: Who are the employees working in the 'Finance' department?"
psql -d employee_tracker -c "SELECT full_name, job_title, email FROM employees WHERE department = 'Finance';"

echo -e "\n📊 Query 5: Retrieve the total number of meetings attended by 'Na Li' in her weekly updates."
psql -d employee_tracker -c "SELECT e.full_name, SUM(ea.meetings_attended) as total_meetings FROM employees e JOIN employee_activities ea ON e.id = ea.employee_id WHERE e.full_name = 'Na Li' GROUP BY e.full_name;"

echo -e "\n📊 Query 6: Which employees worked more than 40 hours during week 1?"
psql -d employee_tracker -c "SELECT e.full_name, ea.hours_worked FROM employees e JOIN employee_activities ea ON e.id = ea.employee_id WHERE ea.week_number = 1 AND ea.hours_worked > 40 ORDER BY ea.hours_worked DESC;"

echo -e "\n📊 Query 7: How many employees does the company have in total?"
psql -d employee_tracker -c "SELECT COUNT(*) as total_employees FROM employees;"

echo -e "\n📊 Query 8: What is the average hours worked by all employees during week 2?"
psql -d employee_tracker -c "SELECT AVG(hours_worked) as average_hours FROM employee_activities WHERE week_number = 2;"

echo -e "\n📊 Query 9: How much total sales revenue has the Sales department generated to date?"
psql -d employee_tracker -c "SELECT SUM(ea.total_sales) as total_sales_revenue FROM employees e JOIN employee_activities ea ON e.id = ea.employee_id WHERE e.department = 'Sales' AND ea.total_sales IS NOT NULL;"

echo -e "\n📊 Query 10: What is the total sales revenue generated by the company during week 1?"
psql -d employee_tracker -c "SELECT SUM(total_sales) as total_week1_sales FROM employee_activities WHERE week_number = 1 AND total_sales IS NOT NULL;"

echo -e "\n📊 Query 11: Who worked the most hours during the first week of September 2024?"
psql -d employee_tracker -c "SELECT e.full_name, ea.hours_worked, cw.start_date FROM employees e JOIN employee_activities ea ON e.id = ea.employee_id JOIN calendar_weeks cw ON ea.week_number = cw.week_number WHERE cw.start_date >= '2024-09-01' AND cw.start_date < '2024-09-08' ORDER BY ea.hours_worked DESC LIMIT 1;"

echo -e "\n📊 Query 12: Which employee attended the most meetings during week 2?"
psql -d employee_tracker -c "SELECT e.full_name, ea.meetings_attended FROM employees e JOIN employee_activities ea ON e.id = ea.employee_id WHERE ea.week_number = 2 ORDER BY ea.meetings_attended DESC LIMIT 1;"

echo -e "\n📊 Query 13: Which employees in the company were hired during a time of industry recession?"
psql -d employee_tracker -c "SELECT full_name, hire_date, department, job_title FROM employees WHERE hire_date >= '2023-01-01' AND hire_date <= '2023-12-31' ORDER BY hire_date;"

echo -e "\n📊 Query 14: Who are the employees that faced challenges with customer retention, and what solutions did they propose?"
psql -d employee_tracker -c "SELECT e.full_name, ea.activities, ea.week_number FROM employees e JOIN employee_activities ea ON e.id = ea.employee_id WHERE ea.activities ILIKE '%customer retention%' OR ea.activities ILIKE '%retention%' ORDER BY e.full_name, ea.week_number;"

echo -e "\n📊 Query 15: Which employees work in roles that likely require data analysis or reporting skills?"
psql -d employee_tracker -c "SELECT full_name, job_title, department FROM employees WHERE job_title ILIKE '%analyst%' OR job_title ILIKE '%data%' OR job_title ILIKE '%report%' OR job_title ILIKE '%financial%' ORDER BY department, full_name;"

echo -e "\n📊 Query 16: List all employees who work in the IT department within the company."
psql -d employee_tracker -c "SELECT full_name, job_title, email, hire_date FROM employees WHERE department = 'IT' ORDER BY full_name;"

echo -e "\n📊 Query 17: Compare the hours worked by 'Wei Zhang' and 'Tao Huang' during week 1."
psql -d employee_tracker -c "SELECT e.full_name, ea.hours_worked, ea.week_number FROM employees e JOIN employee_activities ea ON e.id = ea.employee_id WHERE e.full_name IN ('Wei Zhang', 'Tao Huang') AND ea.week_number = 1 ORDER BY e.full_name;"

echo -e "\n📊 Query 18: Who are the top 3 employees by total hours worked during the last 4 weeks?"
psql -d employee_tracker -c "SELECT e.full_name, SUM(ea.hours_worked) as total_hours FROM employees e JOIN employee_activities ea ON e.id = ea.employee_id WHERE ea.week_number >= 7 GROUP BY e.full_name ORDER BY total_hours DESC LIMIT 3;"

echo -e "\n📊 Query 19: Who achieved the highest sales revenue in a single week, and when?"
psql -d employee_tracker -c "SELECT e.full_name, ea.total_sales, ea.week_number, cw.start_date, cw.end_date FROM employees e JOIN employee_activities ea ON e.id = ea.employee_id JOIN calendar_weeks cw ON ea.week_number = cw.week_number WHERE ea.total_sales IS NOT NULL ORDER BY ea.total_sales DESC LIMIT 1;"

echo -e "\n📊 Query 20: What is the total number of hours worked and average sales revenue for employees in the Business Development department?"
psql -d employee_tracker -c "SELECT SUM(ea.hours_worked) as total_hours_worked, AVG(ea.total_sales) as average_sales_revenue, COUNT(DISTINCT e.id) as employee_count FROM employees e JOIN employee_activities ea ON e.id = ea.employee_id WHERE e.department = 'Business Development';"

echo -e "\n✅ All 20 Queries Complete!"
echo "=============================="
echo "📈 Summary: Tested all example queries from request.md"
echo "🎯 Use these results to verify your LLM system accuracy" 