import os
from openai import OpenAI
import json
from app.llm.query_processor import QueryProcessor

def test_openai_queries():
    # Initialize the OpenAI client and QueryProcessor
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    processor = QueryProcessor()
    
    # Test queries
    test_queries = [
        "How many employees does the company have in total?",
        "What is the email address of the employee who is the Sales Manager?",
        "Which employee in the company works in the Product Development department?",
        "What was the sales revenue of 'Wei Zhang' for the week starting on '2024-08-28'?",
        "Who are the employees working in the 'Finance' department?",
        "Retrieve the total number of meetings attended by 'Na Li' in her weekly updates.",
        "Which employees worked more than 40 hours during week 1?",
        "What is the average hours worked by all employees during week 2?",
        "How much total sales revenue has the Sales department generated to date?",
        "What is the total sales revenue generated by the company during week 1?"
    ]
    
    print("\nTesting OpenAI Integration with QueryProcessor")
    print("----------------------------------------------")
    
    for query in test_queries:
        try:
            # Get SQL from OpenAI
            response = client.chat.completions.create(
                model="gpt-4-turbo",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant that generates SQL queries."},
                    {"role": "user", "content": f"Generate a SQL query for: {query}"}
                ],
                temperature=0.7,
                max_tokens=150
            )
            
            openai_sql = response.choices[0].message.content
            
            # Get SQL from QueryProcessor
            processor_sql = processor._generate_sql_query(query, processor._determine_query_type(query), processor._extract_parameters(query))
            
            # Print results
            print(f"\nQuery: {query}")
            print("OpenAI SQL:", openai_sql)
            print("Processor SQL:", processor_sql)
            print("-" * 80)
            
        except Exception as e:
            print(f"Error processing query '{query}': {str(e)}")
            continue

if __name__ == "__main__":
    test_openai_queries() 