import requests
import json
from typing import List, Dict

BASE_URL = "http://localhost:8000/api/v1"

def test_query(query: str) -> Dict:
    """Test a single query and return the response"""
    response = requests.post(
        f"{BASE_URL}/query",
        json={"query": query}
    )
    return response.json()

def run_all_tests():
    """Run all test queries and print results"""
    test_queries = [
        # Basic employee information
        "What is the email address of the Sales Manager?",
        "Which employee in the company works in the Product Development department?",
        "What is the total sales revenue generated by Wei Zhang in week 2024-08-28?",
        "Which employees work in the Finance department?",
        "How many meetings did Na Li attend?",
        
        # Hours and workload
        "Which employees worked more than 40 hours in week 1?",
        "How many employees are there in the company?",
        "What is the average hours worked by all employees during week 2?",
        "What is the total sales revenue generated by the Sales department?",
        "What is the total sales revenue generated by the company during week 1?",
        
        # Performance metrics
        "Who worked the most hours in weeks 36 and 37?",
        "Which employee attended the most meetings in week 2?",
        "Which employees had below-average sales performance?",
        "What is the sales performance of employees who worked more than 40 hours?",
        "Which employees work in the IT department?",
        
        # Comparative analysis
        "Compare the hours worked by Wei Zhang and Tao Huang in week 1",
        "Who are the top 3 employees by total hours worked during the last 4 weeks?",
        "Which employee achieved the highest sales revenue?",
        "What is the total number of hours worked and average sales revenue for employees in the Business Development department?"
    ]
    
    print("Running all test queries...\n")
    
    for i, query in enumerate(test_queries, 1):
        print(f"\nTest {i}: {query}")
        print("-" * 80)
        
        try:
            result = test_query(query)
            print(f"Response: {result['answer']}")
            print(f"Confidence: {result['confidence']}")
            if 'error' in result['supporting_data']:
                print(f"Error: {result['supporting_data']['error']}")
            print(f"SQL Query: {result['supporting_data'].get('sql_query', 'N/A')}")
        except Exception as e:
            print(f"Error testing query: {str(e)}")
        
        print("-" * 80)

if __name__ == "__main__":
    run_all_tests() 